# docker-compose.yml
version: '3'

services:
  waline:
    container_name: waline
    image: erwinyou/waline:latest
    restart: always
    ports:
      - "8360:8360"
    volumes:
      - ~/waline/data:/app/data
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: 192.168.1.231
      MYSQL_PORT: 3306
      MYSQL_USER: zdy
      MYSQL_PASSWORD: 3.1415926
      MYSQL_DB: waline
      AUTHOR_EMAIL: zdyas@qq.com
      # 未测试
      SITE_NAME: 张登友的博客
      SITE_URL: https://www.zdynb.cn
      SMTP_SERVICE: QQ
      SMTP_USER: zdyas@qq.com
      SMTP_PASS: uykrniysoraohgdb
      SECURE_DOMAINS: www.zdynb.cn,m.zdynb.cn,rs.zdynb.cn,music.zdynb.cn,ts.zdynb.cn,cook.zdynb.cn,api.zdynb.cn,json.zdynb.cn,reg.zdynb.cn,code.zdynb.cn,icon.zdynb.cn,apis.zdynb.cn.conf
      IPQPS: 5
