# docker-compose.yml
version: '3'

services:
  waline:
    container_name: waline
    image: erwinyou/waline:latest
    restart: always
    ports:
      - "8360:8360"
    volumes:
      - ~/waline/data:/app/data
    environment:
      TZ: Asia/Shanghai
      MYSQL_HOST: 192.168.1.231
      MYSQL_PORT: 3306
      MYSQL_USER: zdy
      MYSQL_PASSWORD: 3.1415926
      MYSQL_DB: waline
      AUTHOR_EMAIL: zdyas@qq.com
