# docker-compose.yml
version: '3'

services:
  waline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: waline
    # image: erwinyou/waline
    restart: always
    ports:
      - 8360:8360
    volumes:
      - /Users/zdy/Documents/docker/waline/data:/app/data
    environment:
      MYSQL_HOST: '192.168.1.115'
      MYSQL_DB: 'waline'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: '3.1415926'
      AUTHOR_EMAIL: 'zdyas@qq.com'
      SITE_NAME: '张登友的博客'
      SITE_URL: 'https://www.zdynb.cn'
      SMTP_SERVICE: 'QQ'
      SMTP_USER: 'zdyas@qq.com'
      SMTP_PASS: 'uykrniysoraohgdb'
      SECURE_DOMAINS: 'www.zdynb.cn,rs.zdynb.cn,music.zdynb.cn,reg.zdynb.cn,api.zdynb.cn,json.zdynb.cn,apis.zdynb.cn,icon.zdynb.cn.conf'
      DISABLE_USERAGENT: 'false'
      IPQPS: '10'
